### ISSUE TITLE
Zooming stops at L19

### ISSUE THREAD

**Issue by lucianpls** [vannizhang/wayback#17]
There is data all the way to level 23 in some locations.

**Comment by vannizhang** [comment]
@lucianpls @robert-waterman

It seems this issue was caused by missing `LODs` in MapView's constraints. I added `LODs` to MapView and the app can zoom beyond zoom level 19 now. You can test it on DEV:

https://livingatlasdev.arcgis.com/wayback/#active=46399&mapCenter=18.375%2C-33.941%2C20&localChangesOnly=true
